### ISSUE TITLE
[Question] nRepl support

### ISSUE THREAD

**Issue by artemyarulin** [mjmeintjes/boot-react-native#1]
Hi! 

Great project and great idea how to work with react-packager. Most of the people currently using https://github.com/decker405/figwheel-react-native implementation which loads Closure modules manually, eval it and then establish websocket connection with figwheel (doing eval once again for any new file). 

The problem with this approach that we avoid native packager and for example cannot do simple `require('react-native')` as packager replaces it with full path during file load, while with your approach there shouldn't be such problem, isn't it?

Question is - can we get nrepl support with your approach? I didn't fully understand how things work here, but if we can get nrepl support in a long run we should migrate to the your approach for working with React Native.

Thanks again for the great project

**Comment by mjmeintjes** [comment]
Hi.

Yes, I have been able to get nrepl support using this approach. As far as I remember it was pretty straightforward - simply adding the cljs-repl task to the boot pipeline and then reloading the app. The only problem I encountered was a exception when printing due to the way boot-cljs-repl handles *print-fn* - definitely fixable. I'll add some documentation about [this](https://github.com/mjmeintjes/boot-react-native/issues/3).

I'll push through a few improvements to this project, as well as some [more documentation](https://github.com/mjmeintjes/boot-react-native/issues/2) on the approach later this week.

The basic idea behind it is that it parses the Google Closure deps.js files, and then creates links to the actual library files in node_modules inside the target dir. This allows React Native packager to pick up, include and use files required by goog.require.

**Comment by artemyarulin** [comment]
Thank you! This is awesome. I'm not very familiar with boot - why did you decide to implement RN support with it? Lein is still standard de facto in Clojure(Script) worlds and I wonder - will it be possible to port your way of handling RN to it? 

Thanks again

**Comment by mjmeintjes** [comment]
Hi. I started with Lein, but it seemed to be a bit too all or nothing - seemed like I would have to implement repl support, reload support, etc. With Boot all I did was implement react-native support and I got the rest for free. I also just really like the concepts behind Boot and how easy it is to extend. I've since moved most of my projects over to Boot.

I'm not sure how this approach would work when implementing in Lein, but basically you'll have to:
 * Find some way of modifying output goog/base.js to override the way goog.provide and goog.require works (you can see the code [here](https://github.com/mjmeintjes/boot-react-native/blob/master/resources/mattsum/boot_rn/js/goog_base.js)
 * Parse the created deps.js files to find how Google Closure is going to refer to them via goog.require - you can get the code for this from [here](https://github.com/mjmeintjes/boot-react-native/blob/master/src/mattsum/boot_react_native.clj#L101)
 * Copy/link the files to a directory that React Native Packager is going to look at - easiest I found is to copy them to node_modules inside the output dir
 * Append @providesModule code to each file with the correct Google Closure name that you found previously 

Separately, you'll need some way of starting the React Native packager with the custom Javascript transformer that skips cljs files. Not sure if Lein can do this, but a simple shell script should work.

I'm in the cljsrn Slack room, so ping me if you need any tips. I've spent a lot of time reading the source code for the RN Packager, so I might be able to help if you run into any problems.

**Comment by artemyarulin** [comment]
Thank you very much for such a detailed answer, really awesome!

One last question - Do you plan to continue working with RN and boot? 
I'm currently working on bringing om-next to the world of RN and don't have much free time to migrate the whole thing to lein. And actually if you are saying it will be much more complicated I see no point in doing such work - I guess we should concentrate on one solution and if boot requires it - let's stick with it.

**Comment by mjmeintjes** [comment]
No problem. I'm actually pretty invested already in React Native and boot, as I'm currently building an app for release using these technologies.

I haven't updated this project in a while, but I have been working on it/with it. I'll spend some time this week to pull together the latest changes that I've made.

**Comment by artemyarulin** [comment]
This is really cool - please keep sharing your CLJS<>RN experience here on in cljsrn channel, thanks again!
