### ISSUE TITLE
Discussion: Merge project with re-natal

### ISSUE THREAD

**Issue by vikeri** [mjmeintjes/boot-react-native#48]
As [the essay of the lisp curse](http://www.winestockwebdesign.com/Essays/Lisp_Curse.html) predicts we already have some fragmentation in the very young CLJS RN space: [re-natal](https://github.com/drapanjanas/re-natal) vs [boot-react-native](https://github.com/mjmeintjes/boot-react-native). re-natal is clearly the most popular one if you judge from number of stars and forks here on GitHub. I am pretty sure that as RN usage grows in the CLJS community people are going to want to use boot since it seems to be very popular for the web/node. While the fragmentation between boot and lein are reasonable since they represent different philosophies I do not feel the same is true for re-natal vs boot-react-native and therefore I'd like to raise the question if  these projects could be merged or that re-natal (seemingly being the most popular option) would add boot to the roadmap.

Same issue posted in re-natal: https://github.com/drapanjanas/re-natal/issues/53

**Comment by mjmeintjes** [comment]
Thanks for the article on the lisp curse, found it quite interesting.

I do however think that re-natal and boot-react-native represent different philosophies, because they are based on lein and boot respectively.

I would also expect boot-react-native to be significantly less popular than re-natal because of the popularity of lein vs boot.

I am not opposed to a merge, but I don't know re-natal well enough to understand how easy that would be. And I also don't know whether the re-natal people would be interested in supporting boot, seeing as they use lein mostly.

Another option which I would support would be to see if there are any common libraries to extract from both projects, and then change boot-react-native and re-natal to simpler wrapper scripts for boot and lein.

**Comment by vikeri** [comment]
Yes, since I posted this I've understood that lein and boot are too different for a unified project. But I still believe that we could extract common things into a common lib. Some things that re-natal do that might be lein/boot agnostic:
- lein templates for reagent6, reagent and om.next
- Scripts for switching between real device and emulator

Are there things that boot-react-native does that might be useful for re-natal?

In the future it could be nice to have a testing setup as well. And it would be nice if other RN tooling like microsoft code-push could be used for both as well.

**Comment by vikeri** [comment]
I've now create an (eventually) agnostic lib where we could put some common tools: https://github.com/vikeri/rn-cljs-tools

I wrote it in bash but it might be better to have it writte in js for example so then one may use it with `npm install -g`.
