### ISSUE TITLE
Cannot find entry file index.ios.js in any of the roots

### ISSUE THREAD

**Issue by pesterhazy** [mjmeintjes/boot-react-native#50]
Recent versions don't work for me anymore. When you retrieve the bundle, you get:

```
{"message":"Cannot find entry file index.ios.js in any of the roots: [\"/Users/pe/.boot/cache/tmp/Users/pe/fy/test/example/50r/-5f6t2\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
```

I guess that's because of recent changes moving the build to the boot tempdir?

**Comment by pesterhazy** [comment]
Oh, that's running SimpleExampleApp from a clean clone by the way

**Comment by pesterhazy** [comment]
@samroberton, how did you intend to get index.ios.js into the temp directory?

**Comment by samroberton** [comment]
There's a few sparse notes on PR #46 (as you've probably already seen), but basically my answer is that I didn't.  For the project I'm using this on, I didn't use an index.ios.js -- I used the main.js that comes out of boot's cljs task directly as the entry point to the application.  So I changed the Objective-C entry point in Xcode to ask for main.bundle instead of index.bundle.

I guess either the example app could change to just request main.bundle instead, or as you say, index.ios.js could get copied across to the temp dir as well.

Sorry, I don't have time right this second to go and investigate either of those options, but I'll try to come back to this when I can!  I hadn't realised when I opened the PR that it wasn't working correctly for the example project -- I wasn't testing with the example project, I'm afraid, since I already had my own project I was getting it to work on.

**Comment by pesterhazy** [comment]
@samroberton, thanks for your reply! Changing the entry point to `main.bundle` makes sense; I'll update the example app accordingly.

However, that doesn't seem enough to get it working again, the packager doesn't find that entry point either. Looking at the directory served by the RN packager, it only contains `cljs-rn-transformer.js` and `node_modules`; no main.js anywhere to be found.

I'm guessing there must be some other change to your `build.boot`. Could you share roughly what you're using so I can fix the example and continue work on the React Native update?

**Comment by pesterhazy** [comment]
Figured it out, it was a `nil` `:output-dir` parameter. Above PR fixes it (tested in iOS)
