### ISSUE TITLE
Make example app work without having to change host name from matt-dev

### ISSUE THREAD

**Issue by mjmeintjes** [mjmeintjes/boot-react-native#7]
Example app should work anywhere without having to make source code changes.

**Comment by pesterhazy** [comment]
A first step would be to just use `localhost` everywhere. At least in the iOS simulator, that'll work fine.

**Comment by artemyarulin** [comment]
Two things to note here: `localhost` may work for iOS only. For Android localhost points to the actual device, see more info in this [SO question](http://stackoverflow.com/questions/5806220/how-to-connect-to-my-http-localhost-web-server-from-android-emulator-in-eclips)

But the cool thing that rather than maintaining 3 different IP addresses we can run `adb reverse tcp:3449 tcp:3449` and make localhost work on Android as well
