### ISSUE TITLE
Add .babelrc that ignores cljs-output files

### ISSUE THREAD

**Issue by vikeri** [mjmeintjes/boot-react-native#76]
Since the output of CLJS is already ES3 it is unnecessary to transpile those files with babel. In addition this caused very long npm transform times for us. We solved it by adding a `.babelrc` file to the app folder. Should I submit a PR with that to this example repo as well?

**Comment by pesterhazy** [comment]
Viktor, that sounds like a very valuable thing to add. A PR for the example
app would be great.

**Comment by pesterhazy** [comment]
One more question, how much does adding this for speed things up for you?

On Nov 15, 2016 09:06, "Viktor Eriksson" <notifications@github.com> wrote:

Since the output of CLJS is already ES3 it is unnecessary to transpile
those files with babel. In addition this caused very long npm transform
times for us. We solved it by adding a .babelrc file to the app folder.
Should I submit a PR with that to this example repo as well?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mjmeintjes/boot-react-native/issues/76>, or mute the
thread

**Comment by vikeri** [comment]
Before it took like 6-10 minutes, but now it's down to the normal ~30-60 seconds.
